### PR TITLE
Merge branch 'v0.1.0' of github.com:Living-with-machines/zoonyper into v0.1.0

### PR DESCRIPTION
**Pull request by jmiguelv**
Add a function to check if subjects are disambiguated and output debug information when duplicate subjects are found with the same hash

### CODE REVIEW

**Review by kallewesterling — APPROVED** [review]
This looks great, thank you @jmiguelv !

**Comment by mialondon** [comment]
@kallewesterling do we need to worry about the failing check?

**Comment by kallewesterling** [comment]
It looks unrelated to the code and has to do with the deployment of the docs. I'd encourage setting up a separate issue investigating that, if it affects the final pull into the main branch.

**Comment by mialondon** [comment]
I'm not fussed if you're not!

**Pull request merged**
